-- vim.g.list_of_lsp_server = {"lua_ls", "angularls",  "jsonls", "emmet_ls", "html", "cssls", "vtsls"}
vim.g.list_of_lsp_server = {"lua_ls", "angularls",  "jsonls", "emmet_ls", "html", "cssls", "vtsls"}
-- vim.g.list_of_lsp_server = {"lua_ls", "angularls"}

-- omnisharp
-- angularls
-- html
-- emmet_ls
-- volar
-- vtsls
-- basedpyright
-- marksman
-- lua_ls
-- true
-- ts_ls
-- csharp_ls
-- cssls
-- jsonls
-- eslint
-- yamlls
-- pyright
